auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: siberiawolf
url: http://siberiawolf.github.io
feed: /atom.xml  
author_info: <a href="http://siberiawolf.github.io/">siberiawolf</a>
